baseurl: ""
url: "alljamin.com"

collections:
  pages:
    output: true
    permalink: /:title/

exclude: ["_assets", "gulpfile.js", "node_modules", "package.json", "package-lock.json", ".jekyll-metadata"]

title: Aleksandr Ljamin
tagline: 'Personal portfolio'
description: 'Independent web designer and front-end web developer. Previously <a href="https://techstars.com" target="_blank">Techstars</a> and <a href="https://msdn.microsoft.com/en-au/microsoftstudentpartners.aspx" target="_blank">Microsoft Student Partners</a>.'

github: https://github.com/alljamin
linkedin: https://linkedin.com/in/alljamin
medium: https://medium.com/@alljamin
dribbble: https://dribbble.com/ljamin
stackexchange: https://stackexchange.com/users/6679321/alljamin