baseurl: ""
url: "alljamin.com"

collections:
  pages:
    output: true
    permalink: /:title/

exclude: ["_assets", "gulpfile.js", "node_modules", "package.json", "package-lock.json", ".jekyll-metadata"]

title: Alex Ljamin
tagline: 'Personal portfolio'
description: 'Front-end web developer'

email: aleksandr.lmn@gmail.com
github: https://github.com/alljamin
twitter: https://twitter.com/alljamin
linkedin: https://linkedin.com/in/alljamin
stackexchange: https://stackexchange.com/users/6679321/alljamin